{% set name = "suitcase-jsonl" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8abbe2a566ccec8c71805a75702ed5b53899e27401bda31585b9f83d42464699

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - event-model >=1.8.0
    - suitcase-utils

test:
  requires:
    - python {{ python_min }}
  imports:
    - suitcase.jsonl
    - suitcase.jsonl.tests

about:
  home: https://blueskyproject.io/suitcase
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents to newline-delimited JSON
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-jsonl

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
